AWSTemplateFormatVersion: '2019-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Envios TP3

Resources:
    Envios:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: nodejs8.10
            Events:
                ListEnviosPendientes:
                    Type: Api
                    Properties:
                        Path: /envios/pendientes
                        Method: get
                Envio:
                    Type: Api
                    Properties:
                        Path: /envios/{idEnvio}
                        Method: get
                CreateEnvio:
                    Type: Api
                    Properties:
                        Path: /envios
                        Method: post
                SetEnvioEntregado:
                    Type: Api
                    Properties:
                        Path: /envios/{idEnvio}/entregado
                        Method: post
